# Generated by Django 5.2 on 2025-11-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_rating_bookrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='address',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='website',
        ),
        migrations.AddField(
            model_name='publisher',
            name='birth',
            field=models.IntegerField(blank=True, null=True, default=None),
        ),
    ]
