# Generated by Django 5.2 on 2025-11-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_5_clean_birth_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='birth',
            field=models.IntegerField(blank=True, null=True, default=None),
        ),
    ]
