# Generated by Django 5.2 on 2025-11-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_publisher_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='birth',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
