# Generated by Django 5.2 on 2025-11-08 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_publisher_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='birth',
        ),
    ]
