# Generated by Django 5.2 on 2025-11-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_remove_publisher_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
