# Generated by Django 5.2.8 on 2025-11-12 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_remove_book_category_book_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='book',
            name='price',
        ),
    ]
