# Generated by Django 5.2 on 2025-11-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
