# Generated by Django 5.2.8 on 2025-11-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_total_price_order_book_title_order_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('در انتظار بررسی', 'در انتظار بررسی'), ('تأیید شده', 'تأیید شده'), ('رد شده', 'رد شده')], default='pending', max_length=20),
        ),
    ]
