# Generated by Django 5.2.8 on 2025-11-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='book_title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('در انتظار بررسی', 'در انتظار بررسی'), ('تأیید شده', 'تأیید شده'), ('رد شده', 'رد شده')], default='در انتظار بررسی', max_length=20),
        ),
    ]
